### ISSUE TITLE
Multiple methodnames

### ISSUE THREAD

**Issue by hyperlogin** [timheap/jquery-xmlrpc#10]
Hi there can I know whether I can supply an array of methods to the methodnames?

**Comment by timheap** [comment]
The [XML-RPC spec](http://xmlrpc.scripting.com/spec.html) says that `methodName` must be a single string, so supplying an array of methods for `methodName` would not be valid. Why do you need to do this?

**Comment by hyperlogin** [comment]
because I'm checking whether I can use it to supply a multiple method for the server to return a single compiled response

**Comment by timheap** [comment]
Are you working with a server that already has special support for this non-standard functionality? What would the XML document of this kind of request look like?

**Comment by hyperlogin** [comment]
I think I found out a work around for the problem already thanks

**Comment by timheap** [comment]
If you're talking about [`system.multicall`](http://mirrors.talideon.com/articles/multicall.html), I could be convinced to add explicit support for it

**Comment by hyperlogin** [comment]
Yup it's multicall
