### ISSUE TITLE
base64 encoded Ogg corrupted?

### ISSUE THREAD

**Issue by carlthome** [timheap/jquery-xmlrpc#11]
I'm successfully calling a RPC server with a jquery-xmlrpc client (source below), but the response parameter is corrupt despite being of the correct size. The server takes a base64 encoded Ogg and responds with a base64 encoded Ogg. I have a pure Python RPC client that's working fine, and the jquery-xmlrpc is sending the input correctlywith the exact same server, so is the base64 to ArrayBuffer conversion wonky?

```js
<!DOCTYPE html>
<html>
<head>
<script src="jquery-3.0.0.min.js"></script>
<script src="jquery.xmlrpc.min.js"></script>
<script src="FileSaver.min.js"></script>
</head>
<body>
<input id="filePicker" type="file" accept=".ogg" />
<script>
var handleFileSelect = function(e) {
    var files = e.target.files;
    var file = files[0];
    if (files && file) {
        var reader = new FileReader();
        reader.onload = function(e) {
            $.xmlrpc({
                url: '/RPC2',
                methodName: 'process_audio',
                params: {'audio': e.target.result},
                success: function(response, status, jqXHR) { 
                    saveAs(new Blob([response[0]], {type: 'audio/ogg'}), 'audio.ogg');
                },
                error: function(jqXHR, status, error) { console.error(jqXHR); }
            });
        };
        reader.readAsArrayBuffer(file) 
    }
};
</script>
</body>
</html>
```

**Comment by timheap** [comment]
It is entirely possible that the base64 implementation is broken. It does have tests, but I've not actually used the base64 type when I've used this library.

Could you try and make a minimal XML-RPC response that results in a corrupt file, as well as the uncorrupted file? I will see if I can work out what is going on if you can help me reproduce this.

**Comment by carlthome** [comment]
Alright, unzip [this](https://github.com/timheap/jquery-xmlrpc/files/418163/minimal_xmlrpc_binary_example.zip) and run `python3 server.py`, then visit [http://localhost:8888](http://localhost:8888) in a browser and upload an Ogg file.

It just returns whatever Ogg file you send it. The file size seems about right but the response is corrupted (e.g. cannot be played in a music player).

# Server
```Python
from xmlrpc.server import SimpleXMLRPCServer, SimpleXMLRPCRequestHandler

ip = 'localhost'
port = 8888


def f(x):
    return x.data


class RequestHandler(SimpleXMLRPCRequestHandler):
    rpc_paths = ('/RPC2',)

    def do_OPTIONS(self):
        self.send_response(200)
        self.end_headers()

    def end_headers(self):
        self.send_header("Access-Control-Allow-Headers", 
                         "Origin, X-Requested-With, Content-Type, Accept")
        self.send_header("Access-Control-Allow-Origin", "*")
        SimpleXMLRPCRequestHandler.end_headers(self)


server = SimpleXMLRPCServer((ip, port), RequestHandler)
server.register_function(f, 'f')
server.serve_forever()
```

# Client
```html
<!DOCTYPE html>
<title>Separate</title>
<script src="jquery-3.0.0.min.js"></script>
<script src="jquery.xmlrpc.min.js"></script>
<script src="FileSaver.min.js"></script>
<input id="picker" type="file" accept=".ogg" /><br />
<script>
"use strict;"
var f = function(e) {
	var r = new FileReader();
	r.onload = function(e) {
		$.xmlrpc({
			url: 'http://localhost:8888/RPC2',
			methodName: 'f',
			params: [e.target.result],
			success: function(response, status, jqXHR) { saveAs(new Blob([response[0]]), 'audio.ogg'); },
			error: function(jqXHR, status, error) { console.error(jqXHR); }
		});
	};
	r.readAsArrayBuffer(e.target.files[0])
};
document.getElementById('picker').addEventListener('change', f, false);
</script>
```

**Comment by timheap** [comment]
@carlthome I think I've found the issue, and I think I've fixed it. The Python server was sending back base64 data that was split with whitespace. This library didnt support that, so the data it was extracting was corrupt. I've pushed a fix at 192fad6011afa07038bfe70318169b2da4d5c4b7. Could you test the `jquery.xmlrpc.js` from that commit to see if it works for you?

**Comment by carlthome** [comment]
Yes, great. That fixed it! [Here's](https://tools.ietf.org/html/rfc3548.html#section-2.1) the root of the problem (Python follows the line length limit convention). Could you bump master and add a minified version too?

**Comment by mx-moth** [comment]
I've just pushed version 0.4.4 to master. I should make an NPM package out of this one day, now that that is a thing...
