### ISSUE TITLE
Obtaining empty array in response

### ISSUE THREAD

**Issue by Harish-Ramamurthy** [timheap/jquery-xmlrpc#12]
I am doing the following xml-rpc call.
$.xmlrpc({
      url: '/api/rpc/v1/com.xxx.yyy',
      methodName: 'getParameter',
      params: ['Name'],
      dataFilter: function(data, type) {
          console.log(type);
          console.log(data);  // xml-rpc response is logged(Shown in scrnshot) - Works perfectly fine
        },
      success: function(respone, status, jqXHR) {
        console.log(respone); // Here I get an empty object
      });
});
I ran all the tests and it passed. I believe that the error occurs when the xml-rpc node is converted to the Javascript equivalent.

![xmlrpc_scrnshot](https://cloud.githubusercontent.com/assets/24298462/20801182/49398aec-b7e8-11e6-8ddd-533bda287e0b.png)

      }

**Comment by mx-moth** [comment]
Thanks for the report, @Harish-Ramamurthy.

I added this test case to `tests/tests.documents.js`, replicating the document in your failing example:

```js
deepEqual(
	$.xmlrpc.parseDocument(d(
		'<?xml version="1.0" encoding="UTF-8" ?>' +
		'<methodResponse>' +
			'<params>' +
				'<param><value><string>1</string></value></param>' +
			'</params>' +
		'</methodResponse>')),
	["1"],
	"Can parse a single string response (Issue #12)");
```

I then ran the tet suite in Chrome, and the test passed. It seems that the library is successfully converting the XML document to a JavaScript representation. I am unsure where the error is.

What version of jQuery are you running? Can you provide the request and response that you send / receive from the XMLRPC server?

**Comment by Harish-Ramamurthy** [comment]
Sorry for the late reply as I was in my Christmas vacation. The mistake was on my part. I had to return the data in the dataFilter function. The library works fine and I got the desired output.
