### ISSUE TITLE
Possible inconsistency in decoding response

### ISSUE THREAD

**Issue by CriseX** [timheap/jquery-xmlrpc#8]
So, I have been working on figuring our why xmlrpc call sometimes returns the variables to the success callback correctly and at other times they are inside an array ie. when I expect this: [22, ....] I get [[22], ...]

Here is the method response:
```xml
<?xml version="1.0" encoding="utf-8"?>
<methodResponse>
  <params>
    <param>
      <value>
        <int>24</int>
      </value>
    </param>
  </params>
</methodResponse>
```

Don't know if it makes any difference but when I see the odd decoding, I use it like this:
    `$.when(rpc1(), rpc2()).then(function(r1, r2) { ... });`

But things work as expected with just one rpc call in same setup.

This became a problem when I wanted to do some client side caching of a scalar value, because there can sometimes be nested arrays it is impossible to create a deferred object that would work with the callback in all cases.

**Comment by timheap** [comment]
This seems to be an issue with jQuery and how it handles multiple `Deferred` objects, not with this library. See this code pen for an example or the issue: http://codepen.io/anon/pen/RNLawM?editors=001

Sadly, the arguments sent to the `.then()` function differ depending upon both the number of `Deferred` objects used in `.when()`, and the number of arguments passed to `Deferred.resolve()`. If only one `Deferred` is passed to `.when()`, then `.then()` will receive each argument passed to `resolve` as a separate argument. If `.when()` is passed multiple `Deferred`s, then `.then()` will receive the arguments to each `.resolve()` as its own argument. If there is one argument to `.resolve()`, then that will be in the array as is. If there are multiple, an array of arguments is passed instead. Basically, it is all horrible.

A way of fixing this would be to use:

```javascript
var justData = function(data) { return data; }
$.when(rpc1().then(justData), rpc2().then(justData)).then(function(data1, data2) { ... });
```

If you also need the jqxhr object and other arguments though, it becomes harder.

**Comment by CriseX** [comment]
In case someone stumbles upon this, I might as well post my solution.

What I ended up doing, in order to guarantee that each callback gets returned the arguments in the same way, is to make sure there is always more than one deferred passed to them.

`$.when.apply($, $.map(rpcRequests, rpcMethodCall)).then(function(r1, r2) { ... });

Above rpcRequests is an array of objects passed to xmlrpc and rpcMethodCall is a function that converts any scalar values into appropriate pseudo responses and otherwise returns xmlrpc's promise. As it turns out this way I can also save some typing since the url for all my rpc requests is shared.
