### ISSUE TITLE
Problem with converter in Chrome

### ISSUE THREAD

**Issue by gacarpen** [timheap/jquery-xmlrpc#9]
The xmlrpc.parseDocument converter seems to have some problems parsing structs in chrome.
The source of this, as far as I can tell, appears to be patchy [reduce] (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce) support in chrome as used by the struct decode function:

		return $(node)
			.find('> member')
			.toArray()
			.reduce(function(struct, el) {
				var $el = $(el);
				var key = $el.find('> name').text();
				var value = xmlrpc.parseValue($el.find('> value'));

				struct[key] = value;
				return struct;
			}, {});

This works fine in Firefox.

With a quick modification to avoid using reduce, everything worked fine e.g.

    var struct = {};
		$(node).find('> member').each(
			function(index, el) {
				var $el = $(el);
				var key = $el.find('> name').text();
				var value = xmlrpc.parseValue($el.find('> value'));

				struct[key] = value;
			});
		return struct;

**Comment by timheap** [comment]
Thanks for the bug report, @gacarpen. Unfortunately I can not reproduce this error on any Chrome/Chromium version I have access to, and the test suite is all passing.

Could you attach your Chrome/OS version, any stack traces or errors you are getting, and the incorrect output you are getting? Additionally, you can try running the tests. Assuming Linux/OSX:

```bash
cd jquery-xmlrpc
npm install -g bower
bower install
python -mSimpleHTTPServer 8000
```

Then open `http://localhost:8000/tests/` in your Chrome version that is showing the error, and see if the tests catch the error.

**Comment by gacarpen** [comment]
Thanks for the quick response.

OS: Windows 7/8, OS X, Checked with Chrome Version 43.0.2357.130 most recently.
All of your tests also pass for me, though it may be worth mentioning I'm using the library as part of a tampermonkey script and the way chrome sandboxes things might be confusing the issue.

Get no errors, the reduce function just seems to return something different than it does in firefox (a hideously complicated array of jquery objects from the look of things whereas firefox returns the expected object).
Trying to get equivalent logging form chrome and firefox from:

		var parsed = $(node)
			.find('> member')
			.toArray()
			.reduce(function(struct, el) {
				var $el = $(el);
				var key = $el.find('> name').text();
				var value = xmlrpc.parseValue($el.find('> value'));

				struct[key] = value;
				return struct;
			}, {});
		console.log(parsed)
		return parsed;

gives the following for chrome and firefox respectively (apologies for screenshots):
![chrome](https://cloud.githubusercontent.com/assets/10104943/8544855/c2cca79a-24a0-11e5-979d-e332723f65bb.png)
![firefox](https://cloud.githubusercontent.com/assets/10104943/8544857/c6898880-24a0-11e5-9c46-f8a3ca9925fb.png)

Logging from withing the reduce function seems to fail silently on chrome, making it difficult to further diagnose the issue.

**Comment by timheap** [comment]
Thanks for the extra information. I installed Tampermonkey and tried to replicate your issue, using code taken from the tests. Using the attached script:

```js
// ==UserScript==
// @name         jQuery XMLRPC test
// @namespace    http://your.homepage/
// @version      0.1
// @description  enter something useful
// @author       You
// @match        http://example.com/
// @grant        none
// @require      http://code.jquery.com/jquery-1.11.3.min.js
// @require      https://raw.githubusercontent.com/timheap/jquery-xmlrpc/master/jquery.xmlrpc.min.js
// ==/UserScript==

function el(xml) {
    return $(xml)[0];
}

var node = $.xmlrpc.parseNode(el(
    '<struct>' +
    '<member>' +
    '<name>foo</name>' +
    '<value><i4>4</i4></value>' +
    '</member>' +
    '<member>' +
    '<name>bar</name>' +
    '<value><string>Hello</string></value>' +
    '</member>' +
    '</struct>'));

console.log(node);
```

The correct output appeared in the console:

![tampermonkey](https://cloud.githubusercontent.com/assets/132147/8560847/0670f81a-2560-11e5-91dc-f651351f812c.png)

Could you run the script above in your Chrome environment and see if what result you get? If it works for you, could you attach the script you are working on that causes the error?

**Comment by gacarpen** [comment]
Tried your tampermonkey script and it output the object correctly.

Thinking the only remaining logical explanation was that it must be input related, I tried running your script with the exact input from my own, whereupon yours returned correctly and mine continued not doing so.

At this point, all I can think of is that there's some hidden data that's not getting logged tripping up the function in some way but I've no idea what it could be. Sadly, can't attach the script so can't really think of much else that can be done.

Very much appreciate how responsive and helpful you've been, and thanks for the great library.

**Comment by timheap** [comment]
That is indeed strange. If you get to the bottom of the problem and it does end up being something strange in this library, I am happy for this issue to be reopened. Until then though, I will close this ticket.

You should be able to register your own handler for the `struct` type that uses the code that works for you. I've never actually tried overriding a defined type, but it should work. Try the following code in your project after you have loaded this library:

```javascript
$.xmlrpc.makeType('struct', false, function(value, $xml) {
    // This code is the same
    var $struct = $xml('struct');

    $.each(value, function(name, value) {
        var $name = $xml('name').text(name);
        var $value = $xml('value').append(xmlrpc.toXmlRpc(value, $xml));
        $struct.append($xml('member').append($name, $value));
    });

    return $struct;

}, function(node) {
    // Your modification
    var struct = {};
    $(node).find('> member').each(function(index, el) {
        var $el = $(el);
        var key = $el.find('> name').text();
        var value = xmlrpc.parseValue($el.find('> value'));

        struct[key] = value;
    });
    return struct;
});

```
